PackageIdentifier: Avinashkumar8694.FabrixlyCamSharing
PackageVersion: 1.0.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Avinashkumar8694/zero-cam-sharing/releases/download/v1.0.0/FabrixlyCamSharing-Setup-1.0.0-x64.exe
  InstallerSha256: D28A955A2CF989CC926C68443FB33FFC424EAEF6252C7B7A53C6AC94EA51DCD2
ManifestType: installer
ManifestVersion: 1.6.0
