PackageIdentifier: Avinashkumar8694.ZeroMDroid
PackageVersion: 1.3.2
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Avinashkumar8694/ZeroMDroid-Apps/releases/download/v1.3.2/ZeroMDroid-Setup-1.3.2-x64.exe
  InstallerSha256: 372650C83003633796DA5B7C119F0D5794AE4F4A82F928C8E824FE30408E6B0C
- Architecture: arm64
  InstallerUrl: https://github.com/Avinashkumar8694/ZeroMDroid-Apps/releases/download/v1.3.2/ZeroMDroid-Setup-1.3.2-arm64.exe
  InstallerSha256: B7EC16DAA299E5DB54A6ABEF85B71089EEB163C6C5053A4B9D30D2C86D65BE07
ManifestType: installer
ManifestVersion: 1.6.0
